# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'keyboardNew.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1024, 341)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1024, 300))
        self.centralwidget.setMaximumSize(QtCore.QSize(1024, 300))
        self.centralwidget.setCursor(QtGui.QCursor(QtCore.Qt.SizeAllCursor))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridFrame = QtGui.QFrame(self.centralwidget)
        self.gridFrame.setGeometry(QtCore.QRect(10, 10, 1001, 291))
        self.gridFrame.setObjectName(_fromUtf8("gridFrame"))
        self.gridLayout = QtGui.QGridLayout(self.gridFrame)
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.b14 = QtGui.QPushButton(self.gridFrame)
        self.b14.setObjectName(_fromUtf8("b14"))
        self.gridLayout.addWidget(self.b14, 0, 13, 1, 1)
        self.b13 = QtGui.QPushButton(self.gridFrame)
        self.b13.setObjectName(_fromUtf8("b13"))
        self.gridLayout.addWidget(self.b13, 0, 12, 1, 1)
        self.b12 = QtGui.QPushButton(self.gridFrame)
        self.b12.setObjectName(_fromUtf8("b12"))
        self.gridLayout.addWidget(self.b12, 0, 11, 1, 1)
        self.b21 = QtGui.QPushButton(self.gridFrame)
        self.b21.setObjectName(_fromUtf8("b21"))
        self.gridLayout.addWidget(self.b21, 1, 6, 1, 1)
        self.b28 = QtGui.QPushButton(self.gridFrame)
        self.b28.setObjectName(_fromUtf8("b28"))
        self.gridLayout.addWidget(self.b28, 1, 13, 1, 1)
        self.b67 = QtGui.QPushButton(self.gridFrame)
        self.b67.setObjectName(_fromUtf8("b67"))
        self.gridLayout.addWidget(self.b67, 4, 12, 1, 2)
        self.b32 = QtGui.QPushButton(self.gridFrame)
        self.b32.setObjectName(_fromUtf8("b32"))
        self.gridLayout.addWidget(self.b32, 2, 3, 1, 1)
        self.b39 = QtGui.QPushButton(self.gridFrame)
        self.b39.setObjectName(_fromUtf8("b39"))
        self.gridLayout.addWidget(self.b39, 2, 10, 1, 1)
        self.b18 = QtGui.QPushButton(self.gridFrame)
        self.b18.setObjectName(_fromUtf8("b18"))
        self.gridLayout.addWidget(self.b18, 1, 3, 1, 1)
        self.b27 = QtGui.QPushButton(self.gridFrame)
        self.b27.setObjectName(_fromUtf8("b27"))
        self.gridLayout.addWidget(self.b27, 1, 12, 1, 1)
        self.b23 = QtGui.QPushButton(self.gridFrame)
        self.b23.setObjectName(_fromUtf8("b23"))
        self.gridLayout.addWidget(self.b23, 1, 8, 1, 1)
        self.b20 = QtGui.QPushButton(self.gridFrame)
        self.b20.setObjectName(_fromUtf8("b20"))
        self.gridLayout.addWidget(self.b20, 1, 5, 1, 1)
        self.b33 = QtGui.QPushButton(self.gridFrame)
        self.b33.setObjectName(_fromUtf8("b33"))
        self.gridLayout.addWidget(self.b33, 2, 4, 1, 1)
        self.b36 = QtGui.QPushButton(self.gridFrame)
        self.b36.setObjectName(_fromUtf8("b36"))
        self.gridLayout.addWidget(self.b36, 2, 7, 1, 1)
        self.b15 = QtGui.QPushButton(self.gridFrame)
        self.b15.setObjectName(_fromUtf8("b15"))
        self.gridLayout.addWidget(self.b15, 1, 0, 1, 1)
        self.b37 = QtGui.QPushButton(self.gridFrame)
        self.b37.setObjectName(_fromUtf8("b37"))
        self.gridLayout.addWidget(self.b37, 2, 8, 1, 1)
        self.b34 = QtGui.QPushButton(self.gridFrame)
        self.b34.setObjectName(_fromUtf8("b34"))
        self.gridLayout.addWidget(self.b34, 2, 5, 1, 1)
        self.b41 = QtGui.QPushButton(self.gridFrame)
        self.b41.setObjectName(_fromUtf8("b41"))
        self.gridLayout.addWidget(self.b41, 2, 12, 1, 1)
        self.b19 = QtGui.QPushButton(self.gridFrame)
        self.b19.setObjectName(_fromUtf8("b19"))
        self.gridLayout.addWidget(self.b19, 1, 4, 1, 1)
        self.b29 = QtGui.QPushButton(self.gridFrame)
        self.b29.setObjectName(_fromUtf8("b29"))
        self.gridLayout.addWidget(self.b29, 2, 0, 1, 1)
        self.b30 = QtGui.QPushButton(self.gridFrame)
        self.b30.setObjectName(_fromUtf8("b30"))
        self.gridLayout.addWidget(self.b30, 2, 1, 1, 1)
        self.b17 = QtGui.QPushButton(self.gridFrame)
        self.b17.setObjectName(_fromUtf8("b17"))
        self.gridLayout.addWidget(self.b17, 1, 2, 1, 1)
        self.b16 = QtGui.QPushButton(self.gridFrame)
        self.b16.setObjectName(_fromUtf8("b16"))
        self.gridLayout.addWidget(self.b16, 1, 1, 1, 1)
        self.b71 = QtGui.QPushButton(self.gridFrame)
        self.b71.setObjectName(_fromUtf8("b71"))
        self.gridLayout.addWidget(self.b71, 5, 3, 1, 1)
        self.b38 = QtGui.QPushButton(self.gridFrame)
        self.b38.setObjectName(_fromUtf8("b38"))
        self.gridLayout.addWidget(self.b38, 2, 9, 1, 1)
        self.b22 = QtGui.QPushButton(self.gridFrame)
        self.b22.setObjectName(_fromUtf8("b22"))
        self.gridLayout.addWidget(self.b22, 1, 7, 1, 1)
        self.b26 = QtGui.QPushButton(self.gridFrame)
        self.b26.setObjectName(_fromUtf8("b26"))
        self.gridLayout.addWidget(self.b26, 1, 11, 1, 1)
        self.b31 = QtGui.QPushButton(self.gridFrame)
        self.b31.setObjectName(_fromUtf8("b31"))
        self.gridLayout.addWidget(self.b31, 2, 2, 1, 1)
        self.b64 = QtGui.QPushButton(self.gridFrame)
        self.b64.setObjectName(_fromUtf8("b64"))
        self.gridLayout.addWidget(self.b64, 4, 9, 1, 1)
        self.b61 = QtGui.QPushButton(self.gridFrame)
        self.b61.setObjectName(_fromUtf8("b61"))
        self.gridLayout.addWidget(self.b61, 4, 6, 1, 1)
        self.b58 = QtGui.QPushButton(self.gridFrame)
        self.b58.setObjectName(_fromUtf8("b58"))
        self.gridLayout.addWidget(self.b58, 4, 3, 1, 1)
        self.b54 = QtGui.QPushButton(self.gridFrame)
        self.b54.setObjectName(_fromUtf8("b54"))
        self.gridLayout.addWidget(self.b54, 3, 11, 1, 1)
        self.b50 = QtGui.QPushButton(self.gridFrame)
        self.b50.setObjectName(_fromUtf8("b50"))
        self.gridLayout.addWidget(self.b50, 3, 7, 1, 1)
        self.b40 = QtGui.QPushButton(self.gridFrame)
        self.b40.setObjectName(_fromUtf8("b40"))
        self.gridLayout.addWidget(self.b40, 2, 11, 1, 1)
        self.b51 = QtGui.QPushButton(self.gridFrame)
        self.b51.setObjectName(_fromUtf8("b51"))
        self.gridLayout.addWidget(self.b51, 3, 8, 1, 1)
        self.b68 = QtGui.QPushButton(self.gridFrame)
        self.b68.setObjectName(_fromUtf8("b68"))
        self.gridLayout.addWidget(self.b68, 5, 0, 1, 1)
        self.b70 = QtGui.QPushButton(self.gridFrame)
        self.b70.setObjectName(_fromUtf8("b70"))
        self.gridLayout.addWidget(self.b70, 5, 2, 1, 1)
        self.b62 = QtGui.QPushButton(self.gridFrame)
        self.b62.setObjectName(_fromUtf8("b62"))
        self.gridLayout.addWidget(self.b62, 4, 7, 1, 1)
        self.b43 = QtGui.QPushButton(self.gridFrame)
        self.b43.setObjectName(_fromUtf8("b43"))
        self.gridLayout.addWidget(self.b43, 3, 0, 1, 1)
        self.b24 = QtGui.QPushButton(self.gridFrame)
        self.b24.setObjectName(_fromUtf8("b24"))
        self.gridLayout.addWidget(self.b24, 1, 9, 1, 1)
        self.b69 = QtGui.QPushButton(self.gridFrame)
        self.b69.setObjectName(_fromUtf8("b69"))
        self.gridLayout.addWidget(self.b69, 5, 1, 1, 1)
        self.b45 = QtGui.QPushButton(self.gridFrame)
        self.b45.setObjectName(_fromUtf8("b45"))
        self.gridLayout.addWidget(self.b45, 3, 2, 1, 1)
        self.b46 = QtGui.QPushButton(self.gridFrame)
        self.b46.setObjectName(_fromUtf8("b46"))
        self.gridLayout.addWidget(self.b46, 3, 3, 1, 1)
        self.b47 = QtGui.QPushButton(self.gridFrame)
        self.b47.setObjectName(_fromUtf8("b47"))
        self.gridLayout.addWidget(self.b47, 3, 4, 1, 1)
        self.b59 = QtGui.QPushButton(self.gridFrame)
        self.b59.setObjectName(_fromUtf8("b59"))
        self.gridLayout.addWidget(self.b59, 4, 4, 1, 1)
        self.b57 = QtGui.QPushButton(self.gridFrame)
        self.b57.setObjectName(_fromUtf8("b57"))
        self.gridLayout.addWidget(self.b57, 4, 2, 1, 1)
        self.b25 = QtGui.QPushButton(self.gridFrame)
        self.b25.setObjectName(_fromUtf8("b25"))
        self.gridLayout.addWidget(self.b25, 1, 10, 1, 1)
        self.b48 = QtGui.QPushButton(self.gridFrame)
        self.b48.setObjectName(_fromUtf8("b48"))
        self.gridLayout.addWidget(self.b48, 3, 5, 1, 1)
        self.b42 = QtGui.QPushButton(self.gridFrame)
        self.b42.setObjectName(_fromUtf8("b42"))
        self.gridLayout.addWidget(self.b42, 2, 13, 1, 1)
        self.b66 = QtGui.QPushButton(self.gridFrame)
        self.b66.setObjectName(_fromUtf8("b66"))
        self.gridLayout.addWidget(self.b66, 4, 11, 1, 1)
        self.b65 = QtGui.QPushButton(self.gridFrame)
        self.b65.setObjectName(_fromUtf8("b65"))
        self.gridLayout.addWidget(self.b65, 4, 10, 1, 1)
        self.b44 = QtGui.QPushButton(self.gridFrame)
        self.b44.setObjectName(_fromUtf8("b44"))
        self.gridLayout.addWidget(self.b44, 3, 1, 1, 1)
        self.b49 = QtGui.QPushButton(self.gridFrame)
        self.b49.setObjectName(_fromUtf8("b49"))
        self.gridLayout.addWidget(self.b49, 3, 6, 1, 1)
        self.b53 = QtGui.QPushButton(self.gridFrame)
        self.b53.setObjectName(_fromUtf8("b53"))
        self.gridLayout.addWidget(self.b53, 3, 10, 1, 1)
        self.b55 = QtGui.QPushButton(self.gridFrame)
        self.b55.setObjectName(_fromUtf8("b55"))
        self.gridLayout.addWidget(self.b55, 3, 12, 1, 2)
        self.b52 = QtGui.QPushButton(self.gridFrame)
        self.b52.setObjectName(_fromUtf8("b52"))
        self.gridLayout.addWidget(self.b52, 3, 9, 1, 1)
        self.b63 = QtGui.QPushButton(self.gridFrame)
        self.b63.setObjectName(_fromUtf8("b63"))
        self.gridLayout.addWidget(self.b63, 4, 8, 1, 1)
        self.b35 = QtGui.QPushButton(self.gridFrame)
        self.b35.setObjectName(_fromUtf8("b35"))
        self.gridLayout.addWidget(self.b35, 2, 6, 1, 1)
        self.b1 = QtGui.QPushButton(self.gridFrame)
        self.b1.setObjectName(_fromUtf8("b1"))
        self.gridLayout.addWidget(self.b1, 0, 0, 1, 1)
        self.b9 = QtGui.QPushButton(self.gridFrame)
        self.b9.setObjectName(_fromUtf8("b9"))
        self.gridLayout.addWidget(self.b9, 0, 8, 1, 1)
        self.b11 = QtGui.QPushButton(self.gridFrame)
        self.b11.setObjectName(_fromUtf8("b11"))
        self.gridLayout.addWidget(self.b11, 0, 10, 1, 1)
        self.b4 = QtGui.QPushButton(self.gridFrame)
        self.b4.setObjectName(_fromUtf8("b4"))
        self.gridLayout.addWidget(self.b4, 0, 3, 1, 1)
        self.b5 = QtGui.QPushButton(self.gridFrame)
        self.b5.setObjectName(_fromUtf8("b5"))
        self.gridLayout.addWidget(self.b5, 0, 4, 1, 1)
        self.b8 = QtGui.QPushButton(self.gridFrame)
        self.b8.setObjectName(_fromUtf8("b8"))
        self.gridLayout.addWidget(self.b8, 0, 7, 1, 1)
        self.b2 = QtGui.QPushButton(self.gridFrame)
        self.b2.setObjectName(_fromUtf8("b2"))
        self.gridLayout.addWidget(self.b2, 0, 1, 1, 1)
        self.b73 = QtGui.QPushButton(self.gridFrame)
        self.b73.setObjectName(_fromUtf8("b73"))
        self.gridLayout.addWidget(self.b73, 5, 10, 1, 1)
        self.b6 = QtGui.QPushButton(self.gridFrame)
        self.b6.setObjectName(_fromUtf8("b6"))
        self.gridLayout.addWidget(self.b6, 0, 5, 1, 1)
        self.b56 = QtGui.QPushButton(self.gridFrame)
        self.b56.setObjectName(_fromUtf8("b56"))
        self.gridLayout.addWidget(self.b56, 4, 0, 1, 2)
        self.b60 = QtGui.QPushButton(self.gridFrame)
        self.b60.setObjectName(_fromUtf8("b60"))
        self.gridLayout.addWidget(self.b60, 4, 5, 1, 1)
        self.b72 = QtGui.QPushButton(self.gridFrame)
        self.b72.setObjectName(_fromUtf8("b72"))
        self.gridLayout.addWidget(self.b72, 5, 4, 1, 6)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.b77 = QtGui.QPushButton(self.gridFrame)
        self.b77.setObjectName(_fromUtf8("b77"))
        self.gridLayout_2.addWidget(self.b77, 1, 1, 1, 1)
        self.b75 = QtGui.QPushButton(self.gridFrame)
        self.b75.setObjectName(_fromUtf8("b75"))
        self.gridLayout_2.addWidget(self.b75, 0, 1, 1, 1)
        self.b76 = QtGui.QPushButton(self.gridFrame)
        self.b76.setObjectName(_fromUtf8("b76"))
        self.gridLayout_2.addWidget(self.b76, 1, 0, 1, 1)
        self.b78 = QtGui.QPushButton(self.gridFrame)
        self.b78.setObjectName(_fromUtf8("b78"))
        self.gridLayout_2.addWidget(self.b78, 1, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 5, 12, 1, 2)
        self.b74 = QtGui.QPushButton(self.gridFrame)
        self.b74.setObjectName(_fromUtf8("b74"))
        self.gridLayout.addWidget(self.b74, 5, 11, 1, 1)
        self.b7 = QtGui.QPushButton(self.gridFrame)
        self.b7.setObjectName(_fromUtf8("b7"))
        self.gridLayout.addWidget(self.b7, 0, 6, 1, 1)
        self.b3 = QtGui.QPushButton(self.gridFrame)
        self.b3.setObjectName(_fromUtf8("b3"))
        self.gridLayout.addWidget(self.b3, 0, 2, 1, 1)
        self.b10 = QtGui.QPushButton(self.gridFrame)
        self.b10.setObjectName(_fromUtf8("b10"))
        self.gridLayout.addWidget(self.b10, 0, 9, 1, 1)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(21, 0, 136, 18))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(340, 0, 348, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(930, 0, 64, 18))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(27, 10, 971, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionConnect = QtGui.QAction(MainWindow)
        self.actionConnect.setObjectName(_fromUtf8("actionConnect"))
        self.actionStatus = QtGui.QAction(MainWindow)
        self.actionStatus.setObjectName(_fromUtf8("actionStatus"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionSoftware = QtGui.QAction(MainWindow)
        self.actionSoftware.setObjectName(_fromUtf8("actionSoftware"))
        self.actionDevice = QtGui.QAction(MainWindow)
        self.actionDevice.setObjectName(_fromUtf8("actionDevice"))
        self.actionDeveloper = QtGui.QAction(MainWindow)
        self.actionDeveloper.setObjectName(_fromUtf8("actionDeveloper"))
        self.menuFile.addAction(self.actionConnect)
        self.menuFile.addAction(self.actionStatus)
        self.menuFile.addAction(self.actionExit)
        self.menuAbout.addAction(self.actionSoftware)
        self.menuAbout.addAction(self.actionDevice)
        self.menuAbout.addAction(self.actionDeveloper)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Brain Keyboard", None))
        self.b14.setText(_translate("MainWindow", "Delete", None))
        self.b13.setText(_translate("MainWindow", "+", None))
        self.b12.setText(_translate("MainWindow", "_", None))
        self.b21.setText(_translate("MainWindow", "6", None))
        self.b28.setText(_translate("MainWindow", "Backspace", None))
        self.b67.setText(_translate("MainWindow", "Shift", None))
        self.b32.setText(_translate("MainWindow", "E", None))
        self.b39.setText(_translate("MainWindow", "P", None))
        self.b18.setText(_translate("MainWindow", "3", None))
        self.b27.setText(_translate("MainWindow", "=", None))
        self.b23.setText(_translate("MainWindow", "8", None))
        self.b20.setText(_translate("MainWindow", "5", None))
        self.b33.setText(_translate("MainWindow", "R", None))
        self.b36.setText(_translate("MainWindow", "U", None))
        self.b15.setText(_translate("MainWindow", "`", None))
        self.b37.setText(_translate("MainWindow", "I", None))
        self.b34.setText(_translate("MainWindow", "T", None))
        self.b41.setText(_translate("MainWindow", "]", None))
        self.b19.setText(_translate("MainWindow", "4", None))
        self.b29.setText(_translate("MainWindow", "Tab", None))
        self.b30.setText(_translate("MainWindow", "Q", None))
        self.b17.setText(_translate("MainWindow", "2", None))
        self.b16.setText(_translate("MainWindow", "1", None))
        self.b71.setText(_translate("MainWindow", "Alt", None))
        self.b38.setText(_translate("MainWindow", "O", None))
        self.b22.setText(_translate("MainWindow", "7", None))
        self.b26.setText(_translate("MainWindow", "-", None))
        self.b31.setText(_translate("MainWindow", "W", None))
        self.b64.setText(_translate("MainWindow", ",", None))
        self.b61.setText(_translate("MainWindow", "B", None))
        self.b58.setText(_translate("MainWindow", "X", None))
        self.b54.setText(_translate("MainWindow", "\'", None))
        self.b50.setText(_translate("MainWindow", "J", None))
        self.b40.setText(_translate("MainWindow", "[", None))
        self.b51.setText(_translate("MainWindow", "K", None))
        self.b68.setText(_translate("MainWindow", "Ctrl", None))
        self.b70.setText(_translate("MainWindow", "Win", None))
        self.b62.setText(_translate("MainWindow", "N", None))
        self.b43.setText(_translate("MainWindow", "Caps Lock", None))
        self.b24.setText(_translate("MainWindow", "9", None))
        self.b69.setText(_translate("MainWindow", "Fn", None))
        self.b45.setText(_translate("MainWindow", "S", None))
        self.b46.setText(_translate("MainWindow", "D", None))
        self.b47.setText(_translate("MainWindow", "F", None))
        self.b59.setText(_translate("MainWindow", "C", None))
        self.b57.setText(_translate("MainWindow", "Z", None))
        self.b25.setText(_translate("MainWindow", "0", None))
        self.b48.setText(_translate("MainWindow", "G", None))
        self.b42.setText(_translate("MainWindow", "\\", None))
        self.b66.setText(_translate("MainWindow", "/", None))
        self.b65.setText(_translate("MainWindow", ".", None))
        self.b44.setText(_translate("MainWindow", "A", None))
        self.b49.setText(_translate("MainWindow", "H", None))
        self.b53.setText(_translate("MainWindow", ";", None))
        self.b55.setText(_translate("MainWindow", "Enter", None))
        self.b52.setText(_translate("MainWindow", "L", None))
        self.b63.setText(_translate("MainWindow", "M", None))
        self.b35.setText(_translate("MainWindow", "Y", None))
        self.b1.setText(_translate("MainWindow", "~", None))
        self.b9.setText(_translate("MainWindow", "*", None))
        self.b11.setText(_translate("MainWindow", ")", None))
        self.b4.setText(_translate("MainWindow", "#", None))
        self.b5.setText(_translate("MainWindow", "$", None))
        self.b8.setText(_translate("MainWindow", "&", None))
        self.b2.setText(_translate("MainWindow", "!", None))
        self.b73.setText(_translate("MainWindow", "Alt", None))
        self.b6.setText(_translate("MainWindow", "%", None))
        self.b56.setText(_translate("MainWindow", "Shift", None))
        self.b60.setText(_translate("MainWindow", "V", None))
        self.b72.setText(_translate("MainWindow", "Space", None))
        self.b77.setText(_translate("MainWindow", "Down", None))
        self.b75.setText(_translate("MainWindow", "Up", None))
        self.b76.setText(_translate("MainWindow", "Left", None))
        self.b78.setText(_translate("MainWindow", "Right", None))
        self.b74.setText(_translate("MainWindow", "Ctrl", None))
        self.b7.setText(_translate("MainWindow", "^", None))
        self.b3.setText(_translate("MainWindow", "@", None))
        self.b10.setText(_translate("MainWindow", "(", None))
        self.label.setText(_translate("MainWindow", "Device Status:", None))
        self.label_2.setText(_translate("MainWindow", "Focus on the keys & blink when highlighted to press!", None))
        self.label_3.setText(_translate("MainWindow", "Signal:", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuAbout.setTitle(_translate("MainWindow", "About", None))
        self.actionConnect.setText(_translate("MainWindow", "Connect", None))
        self.actionStatus.setText(_translate("MainWindow", "Status", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionSoftware.setText(_translate("MainWindow", "Software", None))
        self.actionDevice.setText(_translate("MainWindow", "Device", None))
        self.actionDeveloper.setText(_translate("MainWindow", "Developer", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

